### PR TITLE
getImei()

### PR DESCRIPTION
**Pull request by lilei-1**

### CODE REVIEW

**Comment by SimenCodes** [comment]
Won't this crash on all devices not running 8.0+?

**Comment by mitutee** [comment]
I am using 21 API.  
`getImei()` added in API level 26 - package from your branch crashes the build

**Comment by lilei-1** [comment]
I patched my code in my local version. Maybe this not be supported by early version of android API. Make your choice if you have the same issue.

**Comment by mitutee** [comment]
@lilei-1 , there should be a way to fix it without breaking compatibility.

**Comment by SimenCodes** [comment]
#11

**Pull request closed without merging**
